package de.lander.link.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.TextField;

public class LinkLanderFullLayout extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField linkLanderInputBox;
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public LinkLanderFullLayout() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		linkLanderInputBox.focus();

		// Button button = new Button("Click Me");
		// button.addClickListener(new Button.ClickListener() {
		// public void buttonClick(ClickEvent event) {
		// mainLayout.addComponent(new Label("Thank you for clicking"));
		// }
		// });
		// mainLayout.addComponent(button);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// linkLanderInputBox
		linkLanderInputBox = new TextField();
		linkLanderInputBox.setImmediate(false);
		linkLanderInputBox.setWidth("100.0%");
		linkLanderInputBox.setHeight("-1px");
		mainLayout.addComponent(linkLanderInputBox, "top:0.0px;");
		
		return mainLayout;
	}

}
